# 100 NumPy Python Exercises

### Ex 1: Import numpy as `np` and print the version number.

In [23]:
import numpy as np
import pandas as pd
print(np.__version__)
print(pd.__version__)

1.16.4
0.24.2


### Ex 2: Create a 1D array of numbers from 0 to 9

In [6]:
array = np.array(range(10))
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Ex 3: Create a 3×3 numpy array of all True’s

In [9]:
boolean_array = np.full(shape=(3,3), fill_value = True)
boolean_array

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

### Ex 4: How to extract items that satisfy a given condition from 1D array? Extract all odd numbers from `arr`

In [14]:
arr =  np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr_odd = arr[arr % 2 == 1]
arr_odd

array([1, 3, 5, 7, 9])

### Ex 5: How to replace items that satisfy a condition with another value in numpy array? Replace all odd numbers in `arr` with -1

In [19]:
# Permanent help block for function?
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

### Ex 6: How to replace items that satisfy a condition without affecting the original array? Replace all odd numbers in arr with -1 without changing `arr`

In [28]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr_copy = np.where(arr % 2 == 1, -1, arr)
print(arr)
arr_copy

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

### Ex 7: How to reshape an array?  Convert a 1D array to a 2D array with 2 rows

In [38]:
arr = np.arange(10)
print(arr.shape)
np.reshape(arr, (2, -1)) # -1 says to figure out the number of columns automatically

(10,)


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### Ex 8: How to stack two arrays vertically? Stack arrays `a` and `b` vertically

In [43]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

# Method 1
np.concatenate([a, b], axis=0)

# Method 2
np.vstack([a, b])

# Method 3:
np.r_[a, b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### Ex9: How to stack two arrays horizontally? 

In [46]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.concatenate([a, b], axis=1)

#np.hstack([a, b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

### Ex 10: How to generate custom sequences in numpy without hardcoding?

In [61]:
a = np.array([1,2,3])

# Desired output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
b = np.repeat(a, repeats=3) # like seq but specifying times
c = np.tile(a, reps=3) # like seq but specifying 'each'

np.concatenate([b, c], axis=0)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

### Ex 11: How to get common items between two pyton numpy arrays? 

In [66]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

# Desired output: [2, 4]
np.intersect1d(a, b)

array([2, 4])

### Ex12: How to remove one array those items that exist in another?

In [71]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

# Desired output: [1,2,3,4]. From a remove all items in b
np.setdiff1d(a, b)

array([1, 2, 3, 4])

### Ex 13: How to get positions where elements of two arrays match? 

In [78]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

# Desired output: [1,3,5,7]
np.where(a==b)

(array([1, 3, 5, 7]),)

### Ex 14: How to extract all numers between a given range from a numpy array? 

In [84]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

# Get all items between 5 and 10 from a
# Desired output: [6, 9, 10]
a[(a<=10) & (a>=5)]

array([ 6,  9, 10])

### Ex 15: How to make a python function that handles scalars to work on numpy arrays? 

In [90]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

pair_max = np.vectorize(maxx)

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a, b)

array([6, 7, 9, 8, 9, 7, 5])

### Ex 16 and 17: How to swap two columns or rows in a 2D numpy array?

In [95]:
arr = np.arange(9).reshape(3,3)
arr[[1,0,2], :] #rows
arr[:, [1,0,2]] #columns

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

### Ex 18 and 19: How to reverse the rows and columns of 2D array? 

In [105]:
arr = np.arange(9).reshape(3,3)
arr[::-1, :] # reverse rows
arr[:, ::-1] # reverse columns

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

### Ex 20: How to create a 2D array containing random floats between 5 and 10?

In [139]:
rand_arr = np.random.uniform(low=5,high=10, size=(5,3))
rand_arr

array([[6.02099201, 7.3449342 , 8.3138948 ],
       [9.12954464, 6.44958746, 8.00365872],
       [9.62690549, 5.06999108, 5.26978237],
       [9.68245372, 5.62830295, 7.22159067],
       [7.84766276, 6.26509467, 8.14483421]])

### Ex 21: How to print only 3 decimal places in python numpy array?

In [179]:
rand_arr = np.random.random((5,3))
# Solution 1
np.around(rand_arr, 3)

# Solution 2
np.set_printoptions(precision=3)
rand_arr

array([[0.575, 0.891, 0.209],
       [0.185, 0.108, 0.22 ],
       [0.979, 0.812, 0.172],
       [0.816, 0.274, 0.432],
       [0.94 , 0.818, 0.336]])

### Ex 22: How to pretty print a numpy array by supressing scientific notation?

In [180]:
# Create the random array
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3

np.set_printoptions(suppress=True, precision=6)
rand_arr

array([[0.000543, 0.000278, 0.000425],
       [0.000845, 0.000005, 0.000122],
       [0.000671, 0.000826, 0.000137]])

### Ex 23 and 24: How to limit the number of items printed in output of numpy array, or print without truncating?

In [17]:
np.set_printoptions(threshold=100)
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

### Ex 25: How to import a dataset with numbers and texts keeping the text intact in python numpy? 

In [22]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
iris = np.genfromtxt(fname=url, delimiter=",", dtype="object")
iris

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       ...,
       [b'6.5', b'3.0', b'5.2', b'2.0', b'Iris-virginica'],
       [b'6.2', b'3.4', b'5.4', b'2.3', b'Iris-virginica'],
       [b'5.9', b'3.0', b'5.1', b'1.8', b'Iris-virginica']], dtype=object)

### Ex 26: How to extract a particular column from 1D array of tuples? 

In [31]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype="object")
species = np.array([row[4] for row in iris_1d])
species

array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', ...,
       b'Iris-virginica', b'Iris-virginica', b'Iris-virginica'],
      dtype='|S15')

### Ex 27: How to convert a 1D array of tuples to a 2d numpy array?

In [33]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype="object")
iris_1d

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       ...,
       [b'6.5', b'3.0', b'5.2', b'2.0', b'Iris-virginica'],
       [b'6.2', b'3.4', b'5.4', b'2.3', b'Iris-virginica'],
       [b'5.9', b'3.0', b'5.1', b'1.8', b'Iris-virginica']], dtype=object)

In [19]:
?np.genfromtxt

Signature:
np.genfromtxt(
    fname,
    dtype=<class 'float'>,
    comments='#',
    delimiter=None,
    skip_header=0,
    skip_footer=0,
    converters=None,
    missing_values=None,
    filling_values=None,
    usecols=None,
    names=None,
    excludelist=None,
    deletechars=None,
    replace_space='_',
    autostrip=False,
    case_sensitive=True,
    defaultfmt='f%i',
    unpack=None,
    usemask=False,
    loose=True,
    invalid_raise=True,
    max_rows=None,
    encoding='bytes',
)
Docstring:
Load data from a text file, with missing values handled as specified.

Each line past the first `skip_header` lines is split at the `delimiter`
character, and characters following the `comments` character are discarded.

Parameters
----------
fname : file, str, pathlib.Path, list of str, generator
    File, filename, list, or generator to read.  If the filename
    extension is `.gz` or `.bz2`, the file is first decompressed. Note
    that generators must return byte strings in Python 